-- begin CUBASIX_ORDER
alter table CUBASIX_ORDER add constraint FK_CUBASIX_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references CUBASIX_CUSTOMER(ID)^
alter table CUBASIX_ORDER add constraint FK_CUBASIX_ORDER_ON_WORKER foreign key (WORKER_ID) references CUBASIX_WORKER(ID)^
create index IDX_CUBASIX_ORDER_ON_CUSTOMER on CUBASIX_ORDER (CUSTOMER_ID)^
create index IDX_CUBASIX_ORDER_ON_WORKER on CUBASIX_ORDER (WORKER_ID)^
-- end CUBASIX_ORDER
